version: '3.8'

services:
  app:
    build: "."
    container_name: app
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://db;database=HelpDeskApp;verifyServerCertificate=false;useSSL=false;encrypt=false;
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: Admin1234
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - app-network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Admin1234
      - MSSQL_SA_PASSWORD=Admin1234
      - ACCEPT_EULA=Y
      - MSSQL_DB=HelpDeskApp
    ports:
      - "1434:1433"
    networks:
      - app-network
    command: /bin/bash -c " /opt/mssql/bin/sqlservr & sleep 5 && /opt/mssql-tools18/bin/sqlcmd -S db -U sa -P Admin1234 -Q 'CREATE DATABASE HelpDeskApp;' && wait"

networks:
  app-network:
    driver: bridge