spring:
  datasource:
    url: jdbc:sqlserver://localhost;database=HelpDeskApp;encrypt=true;trustServerCertificate=true;
    username: user
    password: user
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
