spring:
  sql:
    init:
      mode: always
    batch:
      jdbc:
        initialize-schema: always
  datasource:
    url: jdbc:sqlserver://db;database=master;verifyServerCertificate=false;useSSL=false;encrypt=false;
    username: user
    password: user123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    defer-datasource-initialization: true


jwt:
  secret: 213fd2s1fe56f1ew5fewfnjkwe4
